
stages:
- stage: BUILD
  jobs:
  - job: "Build"
    steps:
    - checkout: self
      clean: false
    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        Contents: |
          $(Build.SourcesDirectory)/*.pbix
        #  $(Build.SourcesDirectory)/Powershell/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'